import Vue from 'vue'
import Router from 'vue-router'
import All1page from '../view/All1page.vue'
import orgAllPage from '../view/orgAllPage.vue'
import orgResetPage from  '../view/orgResetPage.vue'
import page404 from "../view/404.vue"


Vue.use(Router)

var router = new Router({
  routes: [
    {
      path:'/',
      name:['index',"总览",'pk'],
      component:All1page,
    },
    {
      path:'/All',
      name:['All',"总览"],
      component:All1page,
    },
    //机构的路由
    {
      path:'/organ_preschoolEdu',
      name:['organ','学前教育',"000000XXLB2011031019023910359066098"],
      component:orgResetPage,
    },
    {
      path:'/organ_primaryschool',
      name:['organ',"小学","000000XXLB2010040908555473453211604"],
      component:orgResetPage,
    },
    {
      path:'/organ_initialmiddleschool',
      name:['organ',"初级中学","000000XXLB2012090113413603212072509"],
      component:orgResetPage,
    },
    {
      path:'/organ_middleschool',
      name:['organ',"普通中学","000000XXLB2012090113414886559543145"],
      component:orgResetPage,
    },
    {
      path:'/organ_nineYear',
      name:['organ',"一贯制学校","000000XXLB2010040908555473464879467"],
      component:orgResetPage,
    },
    {
      path:'/organ_specialEdu',
      name:['organ',"特殊教育","000000XXLB2013011810072157046833283"],
      component:orgResetPage,
    },
    {
      path:'/organ_ZZZY',
      name:['organ',"中专或职业教育","000000XXLB2010040908555473470484017"],
      component:orgResetPage
    },
    {
      path:'/organ_adultSchool',
      name:['organ',"成校","000000XXLB2012090113420140919632981"],
      component:orgResetPage
    },
    {
      path:'/organ_otherOrg',
      name:['organ',"其它","8c1980ffdb804f7286b10a7fca945d68"],
      component:orgResetPage
    },
    {
      path:'/organ_BexampleMidschool',
      name:['organ',"区属示范性实验中学","000000XXLB2013011819095672281478518"],
      component:orgResetPage
    },
    {
      path:'/organ_CexampleMidschool',
      name:['organ',"市属示范性实验中学","000000XXLB2013011819095671377554156"],
      component:orgResetPage,
    },
    {
      path:'/organ_managementUnit',
      name:['organ',"管理单位","0ace878d4854452096f31aa691e774ee"],
      component:orgResetPage
    },
    /*{
      path:'/organ_relevantOrg',
      name:['organ',"相关机构"],
      component:orgResetPage
    },
    {
      path:'/organ_privateEdu',
      name:['organ',"纳民小学"],
      component:orgResetPage
    },
    {
      path:'/organ_privateNineEdu',
      name:['organ',"民办九年制"],
      component:orgResetPage
    },
    {
      path:'/organ_nonGovernmentalEdu',
      name:['organ',"民非学校"],
      component:orgResetPage
    },
    {
      path:'/organ_privateSpecialEdu',
      name:['organ',"民办特教"],
      component:orgResetPage
    },
    {
      path:'/organ_privatePreEdu',
      name:['organ',"民办早教"],
      component:orgResetPage
    },
    {
      path:'/organ_privateKindergarten',
      name:['organ',"民办幼儿园"],
      component:orgResetPage
    },*/
    //人员信息的路由
    {
      path:'/person_publicTeach',
      name:['person',"公办教职工"],
      component:orgAllPage
    },
    {
      path:'/person_privateTeach',
      name:['person',"民办教职工"],
      component:orgAllPage
    },
    {
      path:'/person_publicStudent',
      name:['person',"公办在校学生"],
      component:orgAllPage
    },
    {
      path:'/person_privateStudent',
      name:['person',"民办在校学生"],
      component:orgAllPage
    },
    {
      path:'/person_temporary',
      name:['person',"临时工"],
      component:orgAllPage
    },
    {
      path:'/person_substitute',
      name:['person',"代课教师"],
      component:orgAllPage
    },
    //没有找到路由的情况
    {
      path:'/*',
      name:['other',"404"],
      component:page404
    }
  ]
})
export default router;
